### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by ocramz** [DougBurke/hvega#2]
Hi! I just found out about this library, great initiative! 
I've added it to the DataHaskell directory : http://www.datahaskell.org/docs/community/current-environment.html

Could you add it to Stackage, so that compatibility can be tracked more accurately ? https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package 

Thanks a lot!

**Comment by DougBurke** [comment]
I created this essentially as a piece of procrastination, and haven't got around to really using it. So I'd like to see some sort of community build around it (e.g. working out some answers to #1 which I really should reply to) before putting it on stackage.  I realize there is a bit of a chicken-and-egg situation here (if it's on stackage  people may use it), but I don't have much spare time.

**Comment by ocramz** [comment]
I got to know hvega thanks to a user report, so yes, >= 1 people are using this :) If you don't have time for maintaining it perhaps you could consider handing it over to other developers, for example DataHaskell itself.

**Comment by jwoLondon** [comment]
My working knowledge of Haskell is limited so am unlikely to be able to make useful contributions to the Haskell coding, but as the developer of elm-vega, I'd be happy to help/contribute where I can, however this project progresses.

**Comment by ocramz** [comment]
Thanks for your offer @jwoLondon ^_^ BTW @DougBurke this is one example of HVega being in use in an example IHaskell notebook , fyi: https://github.com/DataHaskell/data-glue/blob/master/tutorials/jlab_hvega.ipynb

**Comment by DougBurke** [comment]
Let's see how https://github.com/commercialhaskell/stackage/pull/3883 and https://github.com/commercialhaskell/lts-haskell/issues/153 fair.

**Comment by DougBurke** [comment]
It's in LTS 12.5 - https://www.stackage.org/lts-12.5/package/hvega-0.1.0.3 and https://www.stackage.org/lts-12.5/package/ihaskell-hvega-0.1.0.3 - as well as the nightly build.

I don't know if they are planning any more LTS 11 releases. Do you think it would be useful to add to it too (i.e. ghc 8.2 rather than ghc 8.4), @ocramz?

**Comment by mihaimaruseac** [comment]
A new LTS is building now, I can add it that too.

**Comment by DougBurke** [comment]
Thanks @mihaimaruseac - that would be great (just to be clear, for both `hvega` and `ihaskell-hvega` ;-)
