### ISSUE TITLE
datasets has the wrong type

### ISSUE THREAD

**Issue by mpickering** [DougBurke/hvega#20]
A dataset has to be an inline data source. (See https://vega.github.io/vega-lite/docs/data.html#datasets)

This means the `dataset` combinator currently doesn't work as it allows you to specify any type of datasource and formats them as if they are the argument to the `data` attribute.

**Comment by DougBurke** [comment]
I think I've fixed this in #29 - there is some "ugly" code, in that it's easy to do something wrong, that I've updated. So the type of `datasets` remains the same, but the JSON that gets created should now be correct.

I believe his could be backported to the 0.3 release if that would be useful.

**Comment by DougBurke** [comment]
I am going to assume that #32 has fixed this, but please re-open if that turns out to be hubris on my part.
