### ISSUE TITLE
The 0.4.0.0 release

### ISSUE THREAD

**Issue by DougBurke** [DougBurke/hvega#63]
I've merged a lot of (breaking) changes into the master branch, so I'd appreciate it if people - in particular @BinderDavid and @adamConnerSax - could check to see whether these changes improve things (other than breaking code) or there's still things missing.

I do plan to address part of #17 (expose everything) in 0.4.0.0 but just haven't got to it yet.

**Comment by DougBurke** [comment]
I should note that I'm going to be away from GitHub for a week or so, so won't be particularly responsive!

**Comment by adamConnerSax** [comment]
Happy to try some things over the next few days if I get a chance.  It's easy enough to make sure all the old things work. But do you have a list of what you added/changed in some sort of order of importance or categorized?  Otherwise it's hard to know where to look for things to try.

**Comment by DougBurke** [comment]
I've tried to keep the hvega/CHANGELOG.md up to date, and there's an
"updates" section in the documentation that you can read after 'cabal
v2-haddock' (or something similar).

This is geared more towards the "breaking changes" (ie what you need to
know to get your code to compile with this version).

For the new additions you have to trawl the haddock documentation looking
for the "since 0.4.0.0" label

**Comment by adamConnerSax** [comment]
Gotcha.  I'll recompile with that version and see what breaks but it all looks pretty reasonable from the changelog.  And then I'll see if I can make use of anything new...
Any thoughts about adding some script version support?  Might not matter here but if it does, switching back and forth between versions is going to be annoying...

**Comment by DougBurke** [comment]
@adamConnerSax I assume the script-version support is referring to #28 ? To be honest I don't understand what you mean by "switching back and forth between versions is going to be annoying".

**Comment by DougBurke** [comment]
Current status: pretty-much everything from #29 has now been integrated into the master branch. I have been going through the Vega-Lite gallery and updating notebooks (in #67) which has caught a few extra missing pieces, as well as a number of documentation improvements. I want to get through all the examples just to check, but that's going to take some time (as I'm away next week)

**Comment by DougBurke** [comment]
#86 provides a changelog (I feel I'm close to a release now, but may do some more tweaks)

**Comment by adamConnerSax** [comment]
This is really great work!  I'm looking forward to using it.  I'm sorry I haven't been able to test.  I've been (unhappily) buried in non-plotting bits of code but I am taking a brief vacation back to the plotting bits and I'll try that with the new version as soon as I can...

**Comment by jwoLondon** [comment]
I don't know what bearing the release of Vega-Lite 4.0 will have on your own schedule, but I think there are likely to be several more significant additions to VL. For example, the `image` type is already there in the beta release, but not fully documented or finalized and not yet, at time of writing, integrated into elm-vegalite.

I will be holding back on the tagged elm-vegalite release until there is a little more stability in Vega-Lite 4.0 API.

**Comment by adamConnerSax** [comment]
Recompiled all the things.  Breaking changes were...breaking!  But not bad.  Just the "title" function for me.  
Anyway, it all then compiles and the charts all look good.
Sorry it took me so long to get to this.  Thanks again for all the work!

**Comment by DougBurke** [comment]
Thanks for the review @adamConnerSax@.

**Comment by DougBurke** [comment]
@jwoLondon - thanks for the update.

I plan to make the hevga 0.4 release target version 3 of Vega Lite, as I want to get something out sooner rather than later (and it is a significant update in functionality over hvega 0.3). Then I can think about supporting all the new toys!

**Comment by DougBurke** [comment]
0.4.0.0 has been released
