### ISSUE TITLE
Adding error bars

### ISSUE THREAD

**Issue by adamConnerSax** [DougBurke/hvega#8]
Are you interested in having the error bar/band things added?  I forked the repo, added the minimum necessary (some new mark types, some new mark properties and one new type to support that) and all the necessary labeling and exports.

I also upgraded the schema version to 3.  

And, not in the repo, changed to newer versions in the scripts header in my html.  I could update the docs in the repo for this?

In doing so, I think I changed your whitespacing so it will look like more changes than it is.  But I'm not really sure how to change that back since my emacs setup automatically does some alignment things.

Anyway, once I've tested some and made sure everything one needs is in there, do you want a PR or did you leave that stuff out for some reason that I don't understand yet? (which seems likely!)

**Comment by adamConnerSax** [comment]
Or maybe this is all better handled via x2 and y2 and layers? I see, as I use it, that there's not much extra you get by using the errorbar or errorband functionality.  And then some other things don't work (like selections!).  Is that why you left them out?

**Comment by DougBurke** [comment]
So, I created this module during an extended period of procrastination (it was almost meta-procrastination, in that it was an offshoot of a different piece of procrastination I was doing). That is to say I did the minimum work porting this from the Elm Vega bindings, and haven't had time since to use it to see how the API feels in Haskell (my initial thoughts are that it's clunky since it is not too far removed from just writing JSON, but maybe that's just me). I also haven't had time to keep up with the changes in the Vega/VegaLite landscape (e.g. the v2 to v3 schema work). This is all a long way of saying that you shouldn't read too much into missing functionality in hvega!

I'm happy for PRs, particularly by people who are actually using the module!

**Comment by adamConnerSax** [comment]
Great!  I'm going to play some more and make sure I've added all that's required for errorbar and errorband to work so that it's all in one PR.  
Is it okay if the version change is in there as well?  I'm not sure how to test that.  It works fine for me on the charts I've got working so far, so it looks to be at least mostly backward compatible but I don't know how to insure that.  
It would be nice to have a test suite but I don't think I'm the right person for that job since my experience with vega and grammar-of-graphics is pretty limited.
I really like the module so far!  I find it a little clunky but not nearly enough to dim my happiness at having most of the abilities of vega-lite to hand.  As I make more types of charts--so far I have a chart to show a clustering result and clicking any cluster results in a separate chart displaying the underlying data to zoom to just that cluster, and now I'm working on a scatter + fit chart--I'll think more about how the design might improve if it were less literal.  But I think vega-lite itself is pretty well thought out and short of re-implementing the back-end in Haskell--which would then allow all the functional arguments to "transform" to be substantially more powerful--I'm not sure what you could do.  I guess you could write a DSL that tightened up the notation and semantic relationships? I'll think about that.

**Comment by DougBurke** [comment]
Great - looking forward to it. Submit the PR as you find easiest and then we can work out whether it makes sense to split it into several pieces.

**Comment by jwoLondon** [comment]
While not formally a "test suite", the [test-gallery examples in Elm](https://github.com/gicentre/elm-vegalite/tree/master/test-gallery/src) and [elm-vegalite tests](https://github.com/gicentre/elm-vegalite/tree/master/tests/src) provide a reasonably comprehensive coverage Perhaps these would be helpful as they should be translatable into Haskell.

**Comment by adamConnerSax** [comment]
Ah!  Those look good.  And probably possible to translate via a script?  I don't have time this week but I'll take a longer look next week and see if that's easy...

**Comment by DougBurke** [comment]
I have an example IHaskell notebook in the code at https://github.com/DougBurke/hvega/blob/master/notebooks/VegaLiteGallery.ipynb which I have used for "manual" testing, but it is not as nice as some automated suite, and obviously doesn't catch any new functionality that may be added ;-)

**Comment by adamConnerSax** [comment]
Can the haskell from that just be pulled out into a main that produces one or several html files that can then be visually checked to at least see that all the plots appear and look reasonable?  The notebook thing is cool but fussy and I fear that needing to get a working notebook environment to check would discourage the checking...

**Comment by DougBurke** [comment]
**If** you can get IHaskell working then it's a neat environment for creating these plots, but I do agree that it's hard to set up (I have some nix expressions to try and do this but I haven't tried them recently).

I would rather not lose the notebook, but would like a way to do more-automated tests. I'm not sure if it's worth the effort of trying to keep the two in sync (i.e auto-generate the notebook from the tests), so it probably makes sense to try and create some tests (whether seeded from my notebook or @jwoLondon's elm test set or ...) and then worry about the notebook at some "later date".

**Comment by adamConnerSax** [comment]
Just an update: I've managed better results with rule and area and using y/y2 instead of error bars and error bands.  But I still think they should be in there for completeness and since it does no harm.  Should I revert the spec change in this work and open another issue for that + test cases?  Just seems cleaner that way.

**Comment by DougBurke** [comment]
In general I'm in favor of having "single issue" PRs and issues, so if you think it would be better to split things up then go ahead and do so.

**Comment by DougBurke** [comment]
See #10

**Comment by adamConnerSax** [comment]
Also, if you are curious what I am up to with hvega, there’s a much simpler to use example now inside 

https://github.com/adamConnerSax/Frames-utils <https://github.com/adamConnerSax/Frames-utils>

That library should compile on its own (does for me with ghc 8.6.3 and "cabal-v2-build exe:FrameRegressions").  The FrameRegressions executable produces an html file in the “examples/html” directory with some pretty charts comparing regression results.  It’s mostly for me to explore regression algos and experiment with hvega.  But it illustrates some nice uses of the library. Each of those charts, the overlaid regressions and fits and the parameter charts, are produced fairly generically from a collection of strongly-typed (maybe too strongly-typed!) regression results.  A variety of the chart properties, in particular column names and labels, are derived from the types.

That omits the coolest chart I’ve got so far, the clickable clustering chart.  But I don’t have an example of that one inside this library. Soon, I think.

Adam

**Comment by DougBurke** [comment]
I'm closing this since #10 has finally been merged. The testing discussion above is part of #3.
