### ISSUE TITLE
Some possible enhancements to the Gaia notebook example

### ISSUE THREAD

**Issue by jwoLondon** [DougBurke/hvega#88]
I've had a go at converting your Gaia notebook into a [litvis document with elm-vegalite](https://github.com/gicentre/litvis/blob/master/examples/gaia.md). 

Some of the key changes, which should be convertible back to hvega:

* Added an Aitoff projection using calculate transformations. I also found it easier to create the graticule programatically rather than rely on the geoJSON graticule that can be generated by Vega-Lite.

<img width="600" alt="clusters" src="https://user-images.githubusercontent.com/1846999/64042468-c6d6bb00-cb59-11e9-8d77-7a68e43b166f.png">

* I think the circular mean calculation for cluster centroids is incorrect in that it needs to account for crossing the 180 degree line too. As a result the RA average of ComaBer is slightly too low (it fails to account for some locations >180 degrees). I provide what I think it the correct calculation in my litvis notebook, but you may wish to check.

<img width="611" alt="centroids" src="https://user-images.githubusercontent.com/1846999/64042480-cd653280-cb59-11e9-9c79-c11d8e5f0290.png">

* I sorted the bar chart of star numbers in each cluster and dispensed with the histograms binning by RA.

<img width="366" alt="sortedBars" src="https://user-images.githubusercontent.com/1846999/64042594-15845500-cb5a-11e9-8ec7-899db1e7e56c.png">

* The boxplot can be specified more compactly with the boxplot mark and sorted by median via row faceting.

<img width="483" alt="sortedBoxplots" src="https://user-images.githubusercontent.com/1846999/64042641-39479b00-cb5a-11e9-87d0-20be1152875b.png">

**Comment by DougBurke** [comment]
Sorry - I've been working on the notebooks on a branch for the 0.4 release and have finally got around to merging them to master. Will have to look at this soon!

**Comment by DougBurke** [comment]
I should note that I "combined" the Gaia notebook with your Elm VegaLite walkthrough to create the VegaLite tutorial at https://hackage.haskell.org/package/hvega-0.4.0.0/docs/Graphics-Vega-Tutorials-VegaLite.html

**Comment by DougBurke** [comment]
I've applied most of these to the tutorial. Ta.
