### ISSUE TITLE
pivot

### ISSUE THREAD

**Issue by adamConnerSax** [DougBurke/hvega#98]
I see that though you exposed many more of the transforms, "pivot" is not among them.  Is there a concrete reason or could that be added in the future?

I've started to think that all data should be long rather than wide and my one exception is when handing to off to hvega because there you need it wide.  I've written my own "pivot" for Frames data but it might be nice to have the vega-lite one as well.  

Although it might also be nice to be able to do some Haskell-side transformations on the data when it's in 
```[(T.Text, DataValue)]``` form.  I wonder if it might be better--though not in the style of the library right now--to add a bit of interface to make that simpler?

Thoughts?

**Comment by DougBurke** [comment]
I think `pivot` is a version 4 addition, and I decided that I was sticking to version 3 for `hvega-0.4` (as v4 was still being worked on). The idea was to then update to version 4 in a newer version, but that has slipped me by.

**Comment by adamConnerSax** [comment]
That makes sense.  It's not hard to do on the haskell side, depending how you move data to and from hvega. Let's table it here until you feel ready for upgrading...
